### ISSUE TITLE
PyBluez dependency issue

### ISSUE THREAD

**Issue by andyman410** [Mentalab-hub/explorepy#14]
@bmeatayi 
From our conversation i gathered: There are currently several issues with using this library but no real alternatives exist. 

Python 3 has native bluetooth sockets, however again not on windows it seems. Also this does not allow for things like discovery etc. The other BT libs either depend on PyBluez or there are other issues.

A case could be made for you guys to create your own BT library.

**Comment by hannesfrank** [comment]
I used the prebuild wheels provided in [this comment](https://github.com/pybluez/pybluez/issues/180#issuecomment-408235161) on Windows 10.

**Comment by BigDNormal** [comment]
I just have a problem whit the PyBluez  V0.23, I can read the names and addresses of the Bluetooth devices, but when I try to run the connect function I get this error
 in connect
    bt.connect (self._sockfd, addr, port)
OSError: S
I'm running Python 3.8 on Windows 10
What could I do to solve this issue?

This is my code:

# This project requires PyBluez
from bluetooth import *

#Look for all Bluetooth devices #the computer knows about.
print ("Searching for devices...")
print ("")
#Crea un arreglo de las direcciones y nombres de los dispositivos bluetooth
nearby_devices = discover_devices(lookup_names = True)
print("found %d devices" % len(nearby_devices))

num = 0
print ("Select your device by entering its coresponding number...")
for i in nearby_devices:
	num = num + 1
	print (num,": ",i[1])

#Permite seleccionar el modulo bluetooth previamente conectado a la computadora.
selection = int(input("> ")) - 1
print ("You have selected", nearby_devices[selection][1])
bd_addr = nearby_devices[selection][0]
port = 1
sock = BluetoothSocket(RFCOMM)
sock.connect((bd_addr, port))
print("connected.  type stuff")

while True:
	data = input()
	if len(data) == 0:break
	sock.send(data)

#Cerrar la conexion del socket
sock.close()

**Comment by bmeatayi** [comment]
> I just have a problem whit the PyBluez V0.23, I can read the names and addresses of the Bluetooth devices, but when I try to run the connect function I get this error
> in connect
> bt.connect (self._sockfd, addr, port)
> OSError: S
> I'm running Python 3.8 on Windows 10
> What could I do to solve this issue?
> 
> This is my code:
> 
> # This project requires PyBluez
> from bluetooth import *
> 
> #Look for all Bluetooth devices #the computer knows about.
> print ("Searching for devices...")
> print ("")
> #Crea un arreglo de las direcciones y nombres de los dispositivos bluetooth
> nearby_devices = discover_devices(lookup_names = True)
> print("found %d devices" % len(nearby_devices))
> 
> num = 0
> print ("Select your device by entering its coresponding number...")
> for i in nearby_devices:
> num = num + 1
> print (num,": ",i[1])
> 
> #Permite seleccionar el modulo bluetooth previamente conectado a la computadora.
> selection = int(input("> ")) - 1
> print ("You have selected", nearby_devices[selection][1])
> bd_addr = nearby_devices[selection][0]
> port = 1
> sock = BluetoothSocket(RFCOMM)
> sock.connect((bd_addr, port))
> print("connected. type stuff")
> 
> while True:
> data = input()
> if len(data) == 0:break
> sock.send(data)
> 
> #Cerrar la conexion del socket
> sock.close()

Unfortunately, Pybluez v0.23 is not working on Windows. You can find more info on their GitHub repo and also in this [link](https://github.com/pybluez/pybluez/issues/318).

You can install pybluez v0.22 and it should be running without a problem on Windows 10. Note that the requirement of pybluez v0.22 is different from its new version. Please follow the installation instructions in this [link](https://explorepy.readthedocs.io/en/latest/installation.html#how-to-install-windows).

We have developed our own BT interface in Explorepy v1.0.0 and we will remove pybluez from dependencies in the near future.

**Comment by cihanuyanik** [comment]
explorepy 1.3 has a broken dependency (pybluez). Probably "broken" is not a correct word here, but in Windows 10 environment, this requirement does not even allow to install it properly through pip installation. It directly creates exception in the installation process. 

To bypass this installation error:
1. Download explorepy-1.3.0.tar.gz (current last version) via https://github.com/Mentalab-hub/explorepy/releases
2. Extract it into your project. It does not have to be inside your project, but keep folder structure clean.
3. Go into extracted folder and open "setup.py" file.  Find pybluez requirement insertion line. For version 1.3.0, it is at line 40. Again for this version, change version from 0.22 to 0.23. This edit let you get rid of explorepy installation error. We will not use this package anyway.
4. Execute installation by using setup.py file. --> Assuming you are using a completely clean virtual environment for python installation process: 
    4.1: Install numpy first (pip install numpy), 
    4.2: Then "setup.py install". This will install all packages required by explorepy 1.3.

Now explorepy 1.3 should be sucessfully installed in your virtual python environment.

The tricky part here, 'pybluez' still does not work properly and creates OS errors. But as I said above, we are going to use it.
After importing 'exporepy' in your code set bluetooth interface to "sdk". 
import explorepy
explorepy.set_bt_interface('sdk')


NOTE: This solution (actually it is not a solution, it is just a cheap trick to mislead installation process, I am sure that in the next releases, it will not be necessary) has only been tested on Win10, and venv python. If you are using conda or global interpreter of your system, it may or may not work.

**Comment by bmeatayi** [comment]
> explorepy 1.3 has a broken dependency (pybluez). Probably "broken" is not a correct word here, but in Windows 10 environment, this requirement does not even allow to install it properly through pip installation. It directly creates exception in the installation process.
> 
> To bypass this installation error:
> 
> 1. Download explorepy-1.3.0.tar.gz (current last version) via https://github.com/Mentalab-hub/explorepy/releases
> 2. Extract it into your project. It does not have to be inside your project, but keep folder structure clean.
> 3. Go into extracted folder and open "setup.py" file.  Find pybluez requirement insertion line. For version 1.3.0, it is at line 40. Again for this version, change version from 0.22 to 0.23. This edit let you get rid of explorepy installation error. We will not use this package anyway.
> 4. Execute installation by using setup.py file. --> Assuming you are using a completely clean virtual environment for python installation process:
>    4.1: Install numpy first (pip install numpy),
>    4.2: Then "setup.py install". This will install all packages required by explorepy 1.3.
> 
> Now explorepy 1.3 should be sucessfully installed in your virtual python environment.
> 
> The tricky part here, 'pybluez' still does not work properly and creates OS errors. But as I said above, we are not going to use it.
> After importing 'exporepy' in your code set bluetooth interface to "sdk".
> import explorepy
> explorepy.set_bt_interface('sdk')
> 
> NOTE: This solution (actually it is not a solution, it is just a cheap trick to mislead installation process, I am sure that in the next releases, it will not be necessary) has only been tested on Win10, and venv python. If you are using conda or global interpreter of your system, it may or may not work.

Thanks for your comment. I am just quoting my answer in the previous comment.

> Unfortunately, Pybluez v0.23 is not working on Windows. You can find more info on their GitHub repo and also in this [link](https://github.com/pybluez/pybluez/issues/318).

> You can install pybluez v0.22 and it should be running without a problem on Windows 10. Note that the requirement of pybluez v0.22 is different from its new version. Please follow the installation instructions in this [link](https://explorepy.readthedocs.io/en/latest/installation.html#how-to-install-windows).

Please let me know (with the error log) if you have any problem.
