### ISSUE TITLE
Installation requirement bug, pylsl

### ISSUE THREAD

**Issue by weissjonas** [Mentalab-hub/explorepy#51]
> pip install git+https://github.com/Mentalab-hub/explorepy

> Could not find a version that satisfies the requirement 
pylsl==1.13.1 (from explorepy==0.5.0) (from versions: 1.10.3, 1.10.4, 1.10.5, 1.12.2)
No matching distribution found for pylsl==1.13.1 (from explorepy==0.5.0)

---
on: python 3.6.8
running on Ubuntu 18.04

**Comment by bmeatayi** [comment]
It seems that pylsl==1.13.1 is not available for every platform, despite 1.13.1 is the latest version in Pypi (https://pypi.org/project/pylsl/).
I believe explorepy is also compatible with pylsl older versions (e.g. 1.12.2). You can clone explorepy and edit setup.py and remove pylsl version from it (or change it to 1.12.2).

I think we should rollback this dependency version to the older ones in the next release of explorepy.

**Comment by hannesfrank** [comment]
There is [an issue](https://github.com/labstreaminglayer/liblsl-Python/issues/6) on `pylsl`.

You can try to build `pylsl` yourself. This worked for me on Linux Mint 19.3/Ubuntu 18.04:

```sh
# Make a virtual env of your choice
# ...

# Get liblsl
wget https://github.com/sccn/liblsl/releases/download/1.13.0-b13/liblsl-1.13.0-Linux64-bionic.deb
mkdir liblsl
dpkg -x liblsl-1.13.0-Linux64-bionic.deb liblsl

# Build and install liblsl-Python
git clone https://github.com/labstreaminglayer/liblsl-Python.git
cd liblsl-Python
git checkout v1.13.1
mkdir -p pylsl/lib
cp -L ../liblsl/usr/lib/liblsl64.so pylsl/lib
pip install .

apt install python3-dev libbluetooth-dev  # dependency for pybluez
pip install explorepy
```

**Comment by bmeatayi** [comment]
Version dependency for Pylsl has been removed in #50. So, there shouldn't be any problem after next release.

**Comment by cboulay** [comment]
FYI, I finally got around to updating the CI so it automatically builds and distributes pylsl on all major platforms. Your users will be getting the new version of pypi soon. Please let me know if there are any problems.

**Comment by hacklschorsch** [comment]
Excellent news @cboulay!

I was wondering - maybe @weissjonas' Python is 32 bit? Maybe that's the reason pip can't install pylsl==1.13.1 ?

@weissjonas could you double check? Here's how to find out your Python's bitness?

Please try:

    python -VV

If that doesn't already give the bitness, please try:

    file `which python`

If that still's not saying something about the bitness, here's more methods: https://stackoverflow.com/questions/1405913/how-do-i-determine-if-my-python-shell-is-executing-in-32bit-or-64bit

Thanks!
